# Generated by Django 4.2.30 on 2026-09-02 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('academics', '0002_initial'),
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absence',
            name='attendance_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='attendance.attendancerecord'),
        ),
        migrations.AddField(
            model_name='absence',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='absence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='academics.student'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('class_room', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('attendance_record', 'student')},
        ),
    ]
