# Generated by Django 4.2.30 on 2026-09-14 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0002_initial'),
        ('tenants', '0001_initial'),
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage du scan')),
                ('status', models.CharField(choices=[('PRESENT', "Présent à l'heure"), ('LATE', 'En Retard (scan > 10 min)'), ('ABSENT', 'Absent (Non scanné)')], default='PRESENT', max_length=20)),
                ('minutes_late', models.PositiveIntegerField(default=0)),
                ('parent_notified', models.BooleanField(default=False)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='academics.classroom')),
                ('class_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='academics.classsubject')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='academics.student')),
            ],
            options={
                'ordering': ['-scan_timestamp'],
            },
        ),
    ]
