# Generated by Django 4.2.30 on 2026-09-14 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la salle')),
                ('code', models.CharField(max_length=50, verbose_name='Code salle')),
                ('capacity', models.PositiveIntegerField(default=50, verbose_name='Capacité (élèves)')),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Salle de classe ordinaire'), ('LAB', 'Laboratoire de Sciences'), ('COMPUTER_LAB', 'Salle Informatique'), ('SPORTS', 'Terrain EPS / Sport'), ('HALL', 'Grande Salle / Amphithéâtre')], default='CLASSROOM', max_length=30, verbose_name='Type de salle')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('school', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi / Monday'), (1, 'Mardi / Tuesday'), (2, 'Mercredi / Wednesday'), (3, 'Jeudi / Thursday'), (4, 'Vendredi / Friday'), (5, 'Samedi / Saturday')], default=0, verbose_name='Jour de la semaine')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('is_break', models.BooleanField(default=False, verbose_name='Pause / Récréation')),
                ('slot_order', models.PositiveIntegerField(default=1, verbose_name='Ordre du créneau')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school')),
            ],
            options={
                'ordering': ['day_of_week', 'slot_order', 'start_time'],
                'unique_together': {('school', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Nom de l'emploi du temps")),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon en cours'), ('ACTIVE', 'Emploi du temps officiel actif'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi / Monday'), (1, 'Mardi / Tuesday'), (2, 'Mercredi / Wednesday'), (3, 'Jeudi / Thursday'), (4, 'Vendredi / Friday'), (5, 'Samedi / Saturday')], default=0)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.classroom')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.classsubject')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='timetables.room')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_classes', to=settings.AUTH_USER_MODEL)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetables.timeslot')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetables.timetable')),
            ],
            options={
                'ordering': ['day_of_week', 'time_slot__start_time'],
                'unique_together': {('timetable', 'class_room', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi / Monday'), (1, 'Mardi / Tuesday'), (2, 'Mercredi / Wednesday'), (3, 'Jeudi / Thursday'), (4, 'Vendredi / Friday'), (5, 'Samedi / Saturday')])),
                ('is_available', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_availabilities', to='timetables.timeslot')),
            ],
            options={
                'unique_together': {('school', 'teacher', 'day_of_week', 'time_slot')},
            },
        ),
    ]
