# Generated by Django 4.2.30 on 2026-09-14 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'examen")),
                ('description', models.TextField(blank=True, default='', verbose_name='Consignes & Instructions')),
                ('start_time', models.DateTimeField(verbose_name="Heure d'ouverture")),
                ('end_time', models.DateTimeField(verbose_name='Heure de fermeture')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Durée limite (minutes)')),
                ('total_points', models.FloatField(default=20.0, verbose_name='Barème total (points)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Examen publié')),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='Mélanger les questions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.classroom')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.classsubject')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Date/Heure de début')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='Date/Heure de remise')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Examen en cours'), ('SUBMITTED', 'Copie remise'), ('GRADED', 'Copie corrigée')], default='IN_PROGRESS', max_length=20)),
                ('total_score', models.FloatField(blank=True, null=True, verbose_name='Note finale attribuée')),
                ('integrity_score', models.FloatField(default=100.0, verbose_name="Score d'intégrité (%)")),
                ('auto_submitted', models.BooleanField(default=False, verbose_name='Soumis automatiquement par expiration du temps')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_submissions', to='academics.student')),
            ],
            options={
                'ordering': ['-start_time'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'QCM (Choix Multiple)'), ('SHORT_ANSWER', 'Réponse Courte Textuelle'), ('ESSAY', 'Question Ouverte / Dissertation')], default='MCQ', max_length=30, verbose_name='Type de question')),
                ('text', models.TextField(verbose_name='Énoncé de la question')),
                ('points', models.FloatField(default=2.0, verbose_name='Points attribués')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Options QCM (liste)')),
                ('correct_answer', models.TextField(blank=True, default='', verbose_name='Réponse exacte (pour QCM ou autocorrection)')),
                ('order', models.PositiveIntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExamIntegrityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TAB_BLUR', "Changement d'onglet / Quitte l'écran"), ('WINDOW_FOCUS_LOSS', 'Perte de focus fenêtre'), ('COPY_PASTE_ATTEMPT', 'Tentative de copier / coller'), ('RIGHT_CLICK_ATTEMPT', 'Tentative de clic droit'), ('RAPID_SUBMISSION', 'Réponse soumise anormalement vite')], max_length=50, verbose_name="Type d'événement")),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage exact')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées système')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_logs', to='exams.examsubmission')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, default='', verbose_name="Texte saisi par l'élève")),
                ('selected_options', models.JSONField(blank=True, default=list, verbose_name="Choix de l'élève (QCM)")),
                ('score_granted', models.FloatField(blank=True, null=True, verbose_name='Points accordés')),
                ('teacher_comment', models.TextField(blank=True, default='', verbose_name='Appréciation / Remarque enseignant')),
                ('response_time_seconds', models.PositiveIntegerField(default=0, verbose_name='Temps passé sur la question (sec)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_answers', to='exams.examquestion')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examsubmission')),
            ],
            options={
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
