# Generated by Django 4.2.30 on 2026-09-02 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('edu_system', models.CharField(choices=[('FRANCOPHONE', 'Système Francophone'), ('ANGLOPHONE', 'Anglophone System'), ('BOTH', 'Bilingue / Both Systems')], default='FRANCOPHONE', max_length=20)),
                ('status', models.CharField(choices=[('TRIAL', "Période d'essai (14 jours)"), ('ACTIVE', 'Abonnement Actif'), ('READ_ONLY', 'Lecture Seule (Abonnement requis)'), ('SUSPENDED', 'Suspendu')], default='TRIAL', max_length=20)),
                ('trial_ends_at', models.DateTimeField()),
                ('city', models.CharField(blank=True, default='Douala', max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('director_name', models.CharField(blank=True, default='', max_length=150)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('STARTER', 'Starter (Petites écoles)'), ('PRO', 'Pro (Écoles moyennes)'), ('BUSINESS', 'Business (Grands établissements)'), ('ENTERPRISE', 'Enterprise (Groupes scolaires)')], max_length=20, unique=True)),
                ('price_xaf', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_students', models.PositiveIntegerField(default=300)),
                ('features_description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('EXPIRED', 'Expiré'), ('CANCELLED', 'Annulé')], default='ACTIVE', max_length=20)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.subscriptionplan')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.school')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='XAF', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Succès'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('transaction_ref', models.CharField(max_length=100, unique=True)),
                ('cinetpay_token', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, default='CINETPAY', max_length=50)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.subscriptionplan')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_payments', to='tenants.school')),
            ],
        ),
    ]
